### ISSUE TITLE
To resolve Resource Warning : unclosed file

### ISSUE THREAD

**Issue by abhishek-jain-1999** [elimuinformatics/vcf2fhir#58] opened 2021-04-10 15:57 UTC
## Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Context

* Package Version: Latest
* Operating System: Window 10

## Current Behavior

When ever  conv_region_filename, region_studied_filename, nocall_filename files are provided it results in ResourceWarning: unclosed file 

## Expected Behavior

Those warning should not come

### Steps to Reproduce

Run python -m unittest in terminal or try to run any single test case

**Comment by Rohan-cod** [comment] 2021-04-10 16:00
The issue has been resolved @abhishek-jain-1999.

**Comment by abhishek-jain-1999** [comment] 2021-04-10 16:01
@rhdolin @srgothi92 @Rohan-cod this issue is cause by one of functions of pyranges 

`first_start = open(f).readline().split()[1]`

so to resolve this issue can we just create a function our self that will be made according to our use

**Comment by Rohan-cod** [comment] 2021-04-10 16:02
See #57

**Comment by abhishek-jain-1999** [comment] 2021-04-10 16:03
@Rohan-cod But I am taking about another way to solve it.

**Comment by Rohan-cod** [comment] 2021-04-10 16:04
This is an issue in the pyranges library no in vcf2fhir. pyranges needs to be updated then.

**Comment by Rohan-cod** [comment] 2021-04-10 16:05
[Pyranges](https://pypi.org/project/pyranges/)

**Comment by abhishek-jain-1999** [comment] 2021-04-10 16:06
> so to resolve this issue can we just create a function our self that will be made according to our use

**Comment by Rohan-cod** [comment] 2021-04-10 16:07
Dropping the library cannot be a solution. We can open an issue in [pyranges](https://github.com/biocore-ntnu/pyranges) in this regard.

**Comment by abhishek-jain-1999** [comment] 2021-04-10 16:10
No @Rohan-cod I am not talking about dropping Library I am just asking that can we just create that function our self instead of using pyranges's .

**Comment by Rohan-cod** [comment] 2021-04-10 16:11
If we open an issue in pyranges, don't you think it would be better?

**Comment by Rohan-cod** [comment] 2021-04-10 16:12
According to the good practices in python, we should not reinvent the wheel. Libraries are an important part of python

**Comment by abhishek-jain-1999** [comment] 2021-04-10 16:18
@Rohan-cod I understand your point but again I am not saying we should stop using pyranges,  just a function that is causing this issue . It better to make it rather to wait for it in order to solve this issue.

**Comment by Rohan-cod** [comment] 2021-04-10 16:24
I think the issue is just a warning, and it is not causing any issues in vcf2fhir. If you want you can write the function.

**Comment by Rohan-cod** [comment] 2021-04-10 16:26
I have also opened an issue in pyranges in this regard.

**Comment by Rohan-cod** [comment] 2021-04-10 16:40
It is just my opinion. At the end, it is up to the admins to decide.

**Comment by srgothi92** [comment] 2021-04-10 19:49
> so to resolve this issue can we just create a function our self that will be made according to our use

Can you please share some sample code to get more context to what you are suggesting.

**Comment by abhishek-jain-1999** [comment] 2021-04-10 20:19
so It would work as same as read_bed function but it will resolve the unclosed file issue + it would not need an extra parameter like as _df, nrows which are no use to us.

in convertor.py file
```

read_bed(filename):                
       df = pd.read_csv(filename,
                        dtype={
                               "Chromosome": "category",
                               "Strand": "category"
                                 },
                        header=get_header(filename),
                        sep="\t")    
       df.columns = "Chromosome Start End".spilt()[:df.shape[1]]
       return pyranges.PyRanges(df)


 # it will check if the filename ends with .gz and open the file acc to that without causing unclosed file issue
 # and return the whether the file contains the header or not 
 get header(f):  

                                  
```

**Comment by abhishek-jain-1999** [comment] 2021-04-10 20:21
I am also thinking of checking the file if it contains 3 columns or not

**Comment by srgothi92** [comment] 2021-04-10 20:32
What you suggested is not a bad idea. We can open file ourselves and give only panda dataframe to pyranges. However, I am curious why `pyranges` did not close that file. We can wait for few days to get this addressed upstream, if not addressed we can follow something similar to what you suggested.

**Comment by abhishek-jain-1999** [comment] 2021-04-10 21:05
ya I was also wondering that as the same vcf is also doing that

**Comment by abhishek-jain-1999** [comment] 2021-04-10 21:10
So I can just open PR till then as it is nearly complete

**Comment by srgothi92** [comment] 2021-04-10 21:37
> So I can just open PR till then as it is nearly complete

I would wait until we hear back from upstream. As of now its just warnings and nothing is breaking, so we can wait for few days before we try to address in our code.

**Comment by Rohan-cod** [comment] 2021-04-12 15:30
@srgothi92, @endrebak has agreed to fix the code that was causing the `ResourceWarning` :)

**Comment by endrebak** [comment] 2021-04-12 15:55
0.0.96 should be out now. Feel free to ping me if you find more issues.

**Comment by Rohan-cod** [comment] 2021-04-12 15:59
Sure, @endrebak. :)

**Comment by srgothi92** [comment] 2021-04-12 16:14
We should not close this issue until we try out the new version of `pyranges` and verify that warnings are gone.

**Comment by abhishek-jain-1999** [comment] 2021-04-12 16:29
I have updated the pyranges and now those warnings are gone 
only vcf .reader is left now

**Comment by endrebak** [comment] 2021-04-12 16:29
Is that warning also due to pyranges?

**Comment by srgothi92** [comment] 2021-04-12 16:41
> I have updated the pyranges and now those warnings are gone

Can you please raise a PR for the change. thanks !

**Comment by abhishek-jain-1999** [comment] 2021-04-12 16:57
I think if anyone who runs the project having pyranges version 0.0.96 will not get those warning and for that, I think no change is required in the project itself

**Comment by srgothi92** [comment] 2021-04-12 17:16
> I think if anyone who runs the project having pyranges version 0.0.96 will not get those warning and for that, I think no change is required in the project itself

We would want to add minimum supported version for our library, in this case we can say anything above `0.0.96` is good for this issue to be fixed. Otherwise someone else will get similar warnings and can raise same issue.

**Comment by abhishek-jain-1999** [comment] 2021-04-12 17:24
Okay I will start working on that

**Closed** 2021-04-14 01:22 UTC
